name: Deploy Frontend to Hosting

# menentukan kapan workflow dijalankan
on:
  push:
    branches:
      - main

jobs:

  # nama job bebas
  ftp-deploy:

    # runner environment dari GitHub
    runs-on: ubuntu-latest

    steps:

      # STEP 1
      - name: Checkout Repository
        uses: actions/checkout@v4

      # STEP 2
      - name: Deploy files via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4
        with:
          server: ftp.domainanda.com
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./frontend/
          server-dir: public_html/
